# Конфигурация камеры
resolution: [1024, 768]
exposure_time: 10000
analogue_gain: 50.0
awb_enable: true
ae_enable: false
fps: 60
tuning_file: /usr/share/libcamera/ipa/rpi/pisp/imx290.json
output_path: "captured_images"