defaults:
  - head: head
  - camera: camera
  - car: car
  - _self_

app:
  host: 0.0.0.0
  port: 5000
  debug: false

output:
  directory: "captured_images"
  save_images: true

pca:
  channels: 16
  frequency: 250